import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

// Read from the same place the UI does, so the launcher caption and the
// in-app name can't drift apart.
import { APP_INFO } from './src/data/appInfo';

/* The app ships as an Android package, and a service worker inside one is a
   liability rather than a feature.
 *
 *  Capacitor serves the bundle from https://localhost, so a service worker
 *  registers against that origin and caches the JS. The WebView's storage
 *  survives an app update, so the next release installs new native code
 *  beside a cache still handing out the previous release's bundle. That is
 *  not hypothetical — it is how the back button appeared broken here: the new
 *  APK's plugin swallowed the press while the cached bundle had no listener
 *  to receive it.
 *
 *  Nothing is lost by dropping it. The assets are already on the device
 *  inside the APK, so there is no network to be offline from, and the
 *  manifest is only meaningful to a browser. Set BUILD_PWA=1 to get the
 *  service worker back if the app is ever served over the web. */
const withServiceWorker = process.env.BUILD_PWA === '1';

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      /* `injectManifest` with no register call would still emit a worker;
         disabling outright is what keeps it out of the bundle. */
      injectRegister: withServiceWorker ? 'auto' : null,
      selfDestroying: !withServiceWorker,
      registerType: 'autoUpdate',
      manifest: {
        name: APP_INFO.appName,
        short_name: APP_INFO.shortName,
        description: '열자마자 바로 기록하는 지출 가계부',
        lang: 'ko',
        start_url: '/',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#F0F2F6',
        theme_color: '#7B87F5',
        /* Generated by `pnpm brand` from scripts/brand.mjs. The maskable entry
           is its own file, not the same bitmap tagged twice: a launcher mask
           crops well inside the flat icon's artwork, so it needs the mark
           drawn smaller. */
        icons: [
          { src: 'icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: 'icon-512.png', sizes: '512x512', type: 'image/png' },
          { src: 'favicon.svg', sizes: 'any', type: 'image/svg+xml' },
          {
            src: 'icon-maskable-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
    }),
  ],
});
