import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import { VitePWA } from 'vite-plugin-pwa';

// Read from the same place the UI does, so the launcher caption and the
// in-app name can't drift apart.
import { APP_INFO } from './src/data/appInfo';

export default defineConfig({
  plugins: [
    react(),
    VitePWA({
      registerType: 'autoUpdate',
      manifest: {
        name: APP_INFO.appName,
        short_name: APP_INFO.shortName,
        description: '열자마자 바로 기록하는 지출 가계부',
        lang: 'ko',
        start_url: '/',
        display: 'standalone',
        orientation: 'portrait',
        background_color: '#F0F2F6',
        theme_color: '#7B87F5',
        /* Generated by `pnpm brand` from scripts/brand.mjs. The maskable entry
           is its own file, not the same bitmap tagged twice: a launcher mask
           crops well inside the flat icon's artwork, so it needs the mark
           drawn smaller. */
        icons: [
          { src: 'icon-192.png', sizes: '192x192', type: 'image/png' },
          { src: 'icon-512.png', sizes: '512x512', type: 'image/png' },
          { src: 'favicon.svg', sizes: 'any', type: 'image/svg+xml' },
          {
            src: 'icon-maskable-512.png',
            sizes: '512x512',
            type: 'image/png',
            purpose: 'maskable',
          },
        ],
      },
    }),
  ],
});
